### ISSUE TITLE
mail alert pulling wrong value and does now work

### ISSUE THREAD

**Issue by wilsonmfg** [Nekmo/simple-monitor-alert#38]
https://github.com/Nekmo/simple-monitor-alert/blob/11d6dbd3c0b3b9a210d6435208066f5636f1f44e/alerts/mail.py#L31

this line should be `to = self.config.get('to', 'root@localhost')`
as it, the to config option is ignored and thus does not work

**Comment by Nekmo** [comment]
Fixed! Thanks
